In [4]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Conv1D, Flatten

#### This is Sequential API that allows you to build simple model that is not Complex
#### Its is linear stack of layers where each layers has 1 input tensor and 1 output Tensor

In [9]:
model = Sequential([
    Conv1D(32, kernel_size=3, activation="relu", input_shape=(28, 28)),
    Flatten(),
    Dense(128, activation="relu"),
    Dense(10, activation="softmax") # Output Layer with 10 classes
])

model.compile(optimizer="Adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.summary()

c:\Users\abdim\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_4 (Conv1D)               │ (None, 26, 32)         │         2,720 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 832)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 128)            │       106,624 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 110,634 (432.16 KB)

 Trainable params: 110,634 (432.16 KB)

 Non-trainable params: 0 (0.00 B)

#### Functional API
- This allows you to build a model that is complex. E.g Model with Multiple Inputs and Outputs, Shared Layer and Directed acyclic Graph

In [11]:
from tensorflow.keras import Model, Input
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Concatenate
from tensorflow import keras

In [20]:
# Inputs layer
inputs1 = Input(shape=(28, 28, 3), name="Input_Layer_1")
inputs2 = Input(shape=(32, 32, 3), name="Input_Layer_2")

# Layers for first Input
x1 = Conv2D(32, kernel_size=3, activation="relu")(inputs1)
x1 = Flatten()(x1)
x1 = Dense(128, activation="relu", name="Dense_1")(x1)
x1 = Dense(64, activation="relu", name="Dense_2")(x1)


# Layers for Second Input
x2 = Conv2D(32, kernel_size=3, activation="relu")(inputs2)
x2 = Flatten()(x2)
x2 = Dense(128, activation="relu", name="Dense_3")(x2)
x2 = Dense(64, activation="relu", name="Dense_4")(x2)

# Merging the Layers
merged_layer = Concatenate(name="Merged_layer")([x1, x2])
shared_layer = Dense(32, activation="relu", name="shared_layer")(merged_layer)

output1 = Dense(1, activation="sigmoid", name="output_1")(shared_layer) # Has dieases or not
output2 = Dense(10, activation="sigmoid", name="output_2")(shared_layer) # Which type of diease 10 classes

model = Model(inputs=[inputs1, inputs2], outputs=[output1, output2])
model.compile(
    optimizer="adam",
    loss={
        "output_1": "binary_crossentropy",
        "output_2": "sparse_categorical_crossentropy",
    },
    metrics={
        "output_1": "accuracy",
        "output_2": "accuracy"
    }
)
model.summary()


Model: "functional_7"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ Input_Layer_1       │ (None, 28, 28, 3) │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Input_Layer_2       │ (None, 32, 32, 3) │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_12 (Conv2D)  │ (None, 26, 26,    │        896 │ Input_Layer_1[0]… │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_13 (Conv2D)  │ (None, 30, 30,    │        896 │ Input_Layer_2[0]… │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_16          │ (None, 21632)     │          0 │ conv2d_12[0][0]   │
│ (Flatten)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_17          │ (None, 28800)     │          0 │ conv2d_13[0][0]   │
│ (Flatten)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Dense_1 (Dense)     │ (None, 128)       │  2,769,024 │ flatten_16[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Dense_3 (Dense)     │ (None, 128)       │  3,686,528 │ flatten_17[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Dense_2 (Dense)     │ (None, 64)        │      8,256 │ Dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Dense_4 (Dense)     │ (None, 64)        │      8,256 │ Dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Merged_layer        │ (None, 128)       │          0 │ Dense_2[0][0],    │
│ (Concatenate)       │                   │            │ Dense_4[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared_layer        │ (None, 32)        │      4,128 │ Merged_layer[0][… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ output_1 (Dense)    │ (None, 1)         │         33 │ shared_layer[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ output_2 (Dense)    │ (None, 10)        │        330 │ shared_layer[0][… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 6,478,347 (24.71 MB)

 Trainable params: 6,478,347 (24.71 MB)

 Non-trainable params: 0 (0.00 B)

In [25]:
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense, Conv1D, Flatten, Input


class MyModel(Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1 = Conv1D(6, kernel_size=3, activation="relu")
        self.flatten = Flatten()
        self.dense1 = Dense(128, activation="relu")
        self.dense2 = Dense(64, activation="relu")
        self.output_layer = Dense(1, activation="sigmoid")
    
    def call(self, inputs):
        x = self.conv1(inputs)
        x = self.flatten(x)
        x = self.dense1(x)
        x = self.dense2(x)
        return self.output_layer(x)

model = MyModel()
input_shape = Input(shape=(28, 28))
_ = model(input_shape)
model.build(input_shape)
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.summary()
    

Model: "my_model_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_9 (Conv1D)               │ (None, 26, 6)          │           510 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_22 (Flatten)            │ (None, 156)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 128)            │        20,096 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_26 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_27 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 28,927 (113.00 KB)

 Trainable params: 28,927 (113.00 KB)

 Non-trainable params: 0 (0.00 B)

### Custom Layers in Tensorflow
- Custom Layers help you define unique operations that is not readily available in standard tensorflow libaray.
- Inheriated from Keras.layers.Layer. And Overide the follwing methods.
    - __init__: Initialize the layer and its configuration
    - build: which defines the weights or other parametrs
    - call: that implements forward pass

In [32]:
# Lets design a custom Layers that adds 2 to Each Input Parametrs
import tensorflow as tf
import numpy as np


class AddTwoToLayer(tf.keras.layers.Layer):
    def __init(self, **kwargs):
        super(AddTwoToLayer, self).__init__(**kwargs)
    
    def call(self, inputs):
        return inputs + 2

sample_input = np.array([1, 2, 3, 4, 5])
add_2_to_layer = AddTwoToLayer()
output_s = add_2_to_layer(sample_input)
print("Input: ", sample_input)
print("Output: ", output_s)

Input:  [1 2 3 4 5]
Output:  tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int32)


#### Lets Implement a custom activation function.
- Lets create a custom activation function, piecewise activation function, where output behaves differently depending on Input Value

In [40]:
import tensorflow as tf
from tensorflow.keras.layers import Layer


class PiecewiseActivation(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(PiecewiseActivation, self).__init__(**kwargs)

    def call(self, inputs):
        return tf.where(inputs > 0, inputs**2, 0)

input_data = tf.constant([1, 2, -1, -2])
piecewise_layer = PiecewiseActivation()
output_data = piecewise_layer(input_data)
print("Input: ", input_data.numpy())
print("Output: ", output_data.numpy())

Input:  [ 1  2 -1 -2]
Output:  [1 4 0 0]


### Custom Layer that sacles the input with trainable variable

In [45]:
class ScalingLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(ScalingLayer, self).__init__(**kwargs) # Calls the init method of Parents class tf.keras.layers.Layer to initialize its properties and ensure custom layer iniherits all properties and methods of parent class

    def build(self, input_shape):
        # Intialize the trainble weights
        self.w = self.add_weight(
            name="scale_weight",
            shape=(1, ),
            initializer=tf.keras.initializers.Constant(2),
            trainable=True
        )
        # Intailize trainable Bias
        self.b = self.add_weight(
            name="bias",
            shape=(1, ),
            initializer=tf.keras.initializers.Constant(0)
        )

        super(ScalingLayer, self).build(input_shape) # Triggers the build method of parent class - tf.keras.layers.Layer


    def call(self, inputs):
        return self.w * inputs + self.b
        

input_data = tf.constant([1, 2, 3, 4])
scaled_data = ScalingLayer()
output_3 = scaled_data(input_data)
print("Input data: ", input_data)
print("Output data: ", output_3)

Input data:  tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Output data:  tf.Tensor([2. 4. 6. 8.], shape=(4,), dtype=float32)


In [47]:
input_data = tf.random.normal((3, 2, 2, 2))
input_data

<tf.Tensor: shape=(3, 2, 2, 2), dtype=float32, numpy=
array([[[[-0.7185442 , -1.5164057 ],
         [ 0.9727001 , -0.60311896]],

        [[-0.70818764,  1.3816808 ],
         [ 0.27482268,  0.8994941 ]]],


       [[[ 1.3006775 , -0.08237648],
         [-0.4605889 , -0.02775668]],

        [[ 0.52526677,  1.8376244 ],
         [-1.4108658 ,  1.2404368 ]]],


       [[[ 0.6937569 ,  0.2320289 ],
         [ 0.78514516,  0.25764892]],

        [[ 2.3765547 ,  1.179143  ],
         [-0.7125093 , -1.7034816 ]]]], dtype=float32)>