### Custom Layers in Tensorflow
- Custom Layers help you define unique operations that is not readily available in standard tensorflow libaray.
- Inheriated from Keras.layers.Layer. And Overide the follwing methods.
    - __init__: Initialize the layer and its configuration
    - build: which defines the weights or other parametrs
    - call: that implements forward pass

In [3]:
# Lets design a custom Layers that adds 2 to Each Input Parametrs
import tensorflow as tf
from tensorflow.keras.layers import Layer
import numpy as np


class AddTwoToLayer(tf.keras.layers.Layer):
    def __init(self, **kwargs):
        super(AddTwoToLayer, self).__init__(**kwargs)
    
    def call(self, inputs):
        return inputs + 2

sample_input = np.array([1, 2, 3, 4, 5])
add_2_to_layer = AddTwoToLayer()
output_s = add_2_to_layer(sample_input)
print("Input: ", sample_input)
print("Output: ", output_s)

Input:  [1 2 3 4 5]
Output:  tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int32)


#### Lets Implement a custom activation function.
- Lets create a custom activation function, piecewise activation function, where output behaves differently depending on Input Value

In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Layer


class PiecewiseActivation(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(PiecewiseActivation, self).__init__(**kwargs)

    def call(self, inputs):
        return tf.where(inputs > 0, inputs**2, 0)

input_data = tf.constant([1, 2, -1, -2])
piecewise_layer = PiecewiseActivation()
output_data = piecewise_layer(input_data)
print("Input: ", input_data.numpy())
print("Output: ", output_data.numpy())

Input:  [ 1  2 -1 -2]
Output:  [1 4 0 0]


In [5]:
class ScalingLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(ScalingLayer, self).__init__(**kwargs) # Calls the init method of Parents class tf.keras.layers.Layer to initialize its properties and ensure custom layer iniherits all properties and methods of parent class

    def build(self, input_shape):
        # Intialize the trainble weights
        self.w = self.add_weight(
            name="scale_weight",
            shape=(1, ),
            initializer=tf.keras.initializers.Constant(2),
            trainable=True
        )
        # Intailize trainable Bias
        self.b = self.add_weight(
            name="bias",
            shape=(1, ),
            initializer=tf.keras.initializers.Constant(0)
        )

        super(ScalingLayer, self).build(input_shape) # Triggers the build method of parent class - tf.keras.layers.Layer


    def call(self, inputs):
        return self.w * inputs + self.b
        

input_data = tf.constant([1, 2, 3, 4])
scaled_data = ScalingLayer()
output_3 = scaled_data(input_data)
print("Input data: ", input_data)
print("Output data: ", output_3)

Input data:  tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Output data:  tf.Tensor([2. 4. 6. 8.], shape=(4,), dtype=float32)
