In [1]:
import pandas as pd
from tensorflow import keras
import numpy as np

In [2]:
df = pd.read_csv('sonar_dataset.csv', header=None)

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [5]:
X = df.drop(60, axis=1)
y = df[60]

In [6]:
y.value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [7]:
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [8]:
y.replace({'R': 1, 'M': 0}, inplace=True)

In [9]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: 60, dtype: int64

In [10]:
y.value_counts()

60
0    111
1     97
Name: count, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [12]:
X_train.shape

(166, 60)

In [13]:
len(X_test)

42

In [14]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dense(90, activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])
model.compile(optimizer='adam', metrics=['accuracy'], loss='binary_crossentropy')
model.fit(X_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.6087 - loss: 0.6638
Epoch 2/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7210 - loss: 0.6246 
Epoch 3/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7417 - loss: 0.5749 
Epoch 4/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7312 - loss: 0.5594 
Epoch 5/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7700 - loss: 0.5373
Epoch 6/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7923 - loss: 0.4801
Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8157 - loss: 0.4785
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8493 - loss: 0.4093
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8149 - loss: 0.4435 
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7696 - loss: 0.4403
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8556 - loss: 0.3916
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc

In [15]:
model.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - accuracy: 0.8105 - loss: 0.3959   


[0.4003934860229492, 0.8095238208770752]

In [16]:
y_predicted = model.predict(X_test).reshape(-1)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step


In [17]:
y_predicted[:10]

array([9.9679452e-01, 9.9998254e-01, 1.3318994e-04, 7.0622023e-05,
       9.8265785e-01, 9.9203390e-01, 1.4856625e-04, 9.9999797e-01,
       3.6541861e-03, 3.5817367e-03], dtype=float32)

In [18]:
y_pred = np.round(y_predicted)

In [19]:
y_pred[:10]

array([1., 1., 0., 0., 1., 1., 0., 1., 0., 0.], dtype=float32)

In [20]:
y_test[:10]

70     1
25     1
198    0
196    0
94     1
49     1
133    0
51     1
117    0
130    0
Name: 60, dtype: int64

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.78      0.82        23
           1       0.76      0.84      0.80        19

    accuracy                           0.81        42
   macro avg       0.81      0.81      0.81        42
weighted avg       0.81      0.81      0.81        42



#### Precision(Class 0) => Out of all predicted values with 0, 83% are correct
#### Recall(class 0) => Out of all true values with 0, the model predict 87% correct

In [23]:
y_test.shape

(42,)

In [47]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(90, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1,activation='sigmoid')
])
model.compile(optimizer='adam', metrics=['accuracy'], loss='binary_crossentropy')
model.fit(X_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.4612 - loss: 0.7372 
Epoch 2/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4574 - loss: 0.7513 
Epoch 3/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5622 - loss: 0.6927
Epoch 4/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5483 - loss: 0.6714 
Epoch 5/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6342 - loss: 0.6720
Epoch 6/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5991 - loss: 0.6752 
Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6511 - loss: 0.6429 
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6011 - loss: 0.6578
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7110 - loss: 0.6118
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6025 - loss: 0.6472  
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6752 - loss: 0.6227  
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - 

In [51]:
## After dropout is the acccuracy of test data increase
model.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8894 - loss: 0.2941


[0.2960875928401947, 0.8809523582458496]

In [55]:
y_predicted = model.predict(X_test).reshape(-1)
y_predicted = np.round(y_predicted)
y_predicted[:10]

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 


array([1., 1., 0., 0., 1., 1., 0., 1., 0., 0.], dtype=float32)

In [57]:
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

           0       0.82      1.00      0.90        23
           1       1.00      0.74      0.85        19

    accuracy                           0.88        42
   macro avg       0.91      0.87      0.88        42
weighted avg       0.90      0.88      0.88        42

