# New Section

In [12]:
import tensorflow_text as text
import tensorflow_hub as hub
import tensorflow as tf

In [13]:
text_test = ["nice movie indeed!", "I love python programming"]
processor_url = "https://kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-preprocess/3"
encoder_url = "https://www.kaggle.com/models/tensorflow/bert/TensorFlow2/bert-en-uncased-l-12-h-768-a-12/2"
preprocessor = hub.KerasLayer(processor_url)
text_preprocessed = preprocessor(text_test)
text_preprocessed.keys()

dict_keys(['input_mask', 'input_type_ids', 'input_word_ids'])

In [14]:
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['sequence_output', 'pooled_output', 'default', 'encoder_outputs'])

In [18]:
bert_results["pooled_output"] # Output the vector represenation of the entire sentence -> Good for task like sentiment classification

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[ 0.31745428, -0.35284653,  0.91617215, ..., -0.5903159 ,
         0.2398101 ,  0.9947231 ],
       [ 0.3991409 , -0.14203501,  0.9058576 , ..., -0.78319436,
         0.17452335,  0.9984515 ]], dtype=float32)>

In [27]:
len(bert_results["sequence_output"][0][0]) # This output the vector representation of each token in the input sequence

768

In [25]:
len(bert_results["sequence_output"]) # Number of batch or sentence

2

In [31]:
len(bert_results["sequence_output"][0]) # The Length of tokens an entire sentence

128

In [34]:
bert_results["sequence_output"][0]

<tf.Tensor: shape=(128, 768), dtype=float32, numpy=
array([[-0.2543299 ,  0.4136645 ,  0.11988475, ...,  0.05838131,
        -0.19118862, -0.36168373],
       [ 0.5150734 , -0.05045756,  0.26351944, ...,  0.30420828,
        -0.00806616,  0.24090753],
       [-0.07662039,  0.20958927,  0.16420493, ..., -0.19253062,
        -0.28244776, -0.5104307 ],
       ...,
       [ 0.13603824,  0.5397673 ,  0.44022825, ..., -0.2927473 ,
         0.20739809,  0.28214955],
       [-0.12290147,  0.10083847,  0.32473522, ...,  0.09814872,
         0.09474888,  0.3179149 ],
       [-0.09862508,  0.6374589 ,  0.09015322, ..., -0.08469819,
        -0.10294732, -0.26600337]], dtype=float32)>

In [37]:
bert_results["sequence_output"][0] # Representaion of first token in the first sequence input

<tf.Tensor: shape=(128, 768), dtype=float32, numpy=
array([[-0.2543299 ,  0.4136645 ,  0.11988475, ...,  0.05838131,
        -0.19118862, -0.36168373],
       [ 0.5150734 , -0.05045756,  0.26351944, ...,  0.30420828,
        -0.00806616,  0.24090753],
       [-0.07662039,  0.20958927,  0.16420493, ..., -0.19253062,
        -0.28244776, -0.5104307 ],
       ...,
       [ 0.13603824,  0.5397673 ,  0.44022825, ..., -0.2927473 ,
         0.20739809,  0.28214955],
       [-0.12290147,  0.10083847,  0.32473522, ...,  0.09814872,
         0.09474888,  0.3179149 ],
       [-0.09862508,  0.6374589 ,  0.09015322, ..., -0.08469819,
        -0.10294732, -0.26600337]], dtype=float32)>

In [38]:
bert_results["encoder_outputs"][0]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.06800605, -0.10598262, -0.13105674, ..., -0.18217973,
         -0.08342227,  0.04813497],
        [ 0.29170883, -0.49296558,  0.22882177, ...,  1.0974519 ,
         -1.1352427 ,  0.38380682],
        [-0.7376857 , -1.0193546 , -0.39133024, ...,  0.5155023 ,
          0.06112364,  0.07297958],
        ...,
        [ 0.60619855,  0.3991071 ,  0.42633742, ..., -0.2355206 ,
          0.3889828 , -0.3429474 ],
        [ 0.6589593 ,  0.5151232 ,  0.36015022, ..., -0.26972637,
          0.43857104, -0.27134383],
        [ 0.65913284,  0.54804575,  0.33734426, ..., -0.14543416,
          0.49989974, -0.23330125]],

       [[ 0.02516399, -0.16400944, -0.04662891, ..., -0.2618655 ,
         -0.11140703,  0.15489224],
        [ 0.37214527,  0.7362576 , -0.37717193, ...,  0.6425172 ,
         -0.6226271 ,  0.05394955],
        [-1.3278612 , -0.0473671 ,  0.47504824, ...,  0.01998842,
         -0.4994462 ,  1.6198301 ],
        ...,

In [39]:
bert_results["encoder_outputs"][11] # The output of the last encoder which

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-0.2543299 ,  0.4136645 ,  0.11988475, ...,  0.05838131,
         -0.19118862, -0.36168373],
        [ 0.5150734 , -0.05045756,  0.26351944, ...,  0.30420828,
         -0.00806616,  0.24090753],
        [-0.07662039,  0.20958927,  0.16420493, ..., -0.19253062,
         -0.28244776, -0.5104307 ],
        ...,
        [ 0.13603824,  0.5397673 ,  0.44022825, ..., -0.2927473 ,
          0.20739809,  0.28214955],
        [-0.12290147,  0.10083847,  0.32473522, ...,  0.09814872,
          0.09474888,  0.3179149 ],
        [-0.09862508,  0.6374589 ,  0.09015322, ..., -0.08469819,
         -0.10294732, -0.26600337]],

       [[ 0.05904213, -0.21204117, -0.13617851, ...,  0.43750256,
          0.5026955 , -0.35996336],
        [ 0.6707301 ,  0.14048877, -0.09224142, ...,  0.42108783,
          0.41119042, -0.5584124 ],
        [ 0.17798199, -0.49039   , -0.38667142, ...,  0.1257011 ,
         -0.2774938 , -0.15996684],
        ...,